# yaml-language-server: $schema=../../src/asqi/schemas/asqi_suite_config.schema.json
suite_name: "CV Check"
test_suite:
  - name: "cv_eval"
    image: "my-registry/cv_tester:latest"
    target_suts:
      - "huggingface_object_detection" # object_detection , roboflow_object_detection, huggingface_object_detection, ultralytics_object_detection
    volumes:
      input : "/home/ubuntu/code/asqi/test_data/input" # Mac path : "/workspaces/asqi/test_data/input"
      output : "/home/ubuntu/code/asqi/test_data/output" # Mac path : "/workspaces/asqi/test_data/output"
    params:
      input_image_path : "/input/images"
      groundtruth_path : "/input/gt"