# yaml-language-server: $schema=../../src/asqi/schemas/asqi_suite_config.schema.json
suite_name: "CV Check"
test_suite:
  - name: "cv_eval"
    image: "my-registry/cv_tester:latest"
    systems_under_test:
      - "object_detection"
    volumes:
      input: "/workspaces/asqi/test_data/input"
      output: "/workspaces/asqi/test_data/outputs"
    params:
      input_image_path: "/input/images"
      groundtruth_path: "/input/gt"
