# yaml-language-server: $schema=../../src/asqi/schemas/asqi_suite_config.schema.json
suite_name: "Security Testing Suite with Garak"
test_suite:
  # Basic security probes using garak
  - name: "garak_encoding_probe"
    image: "asqiengineer/test-container:garak-latest"
    systems_under_test:
      - "openai_gpt4o_mini"
    params:
      probes: ["encoding.InjectHex"]
      generations: 1

  # Prompt injection attacks testing
  - name: "garak_prompt_injection"
    image: "asqiengineer/test-container:garak-latest"
    systems_under_test:
      - "openai_gpt4o_mini"
    params:
      probes: ["dan"]
      generations: 1
