# yaml-language-server: $schema=../../src/asqi/schemas/asqi_suite_config.schema.json
suite_name: "Security Testing Suite with Garak"
test_suite:
  # Basic security probes using garak
  - id: "garak_encoding_probe"
    name: "garak_encoding_probe"
    image: "asqiengineer/test-container:garak-latest"
    systems_under_test:
      - "openai_gpt4o_mini"
    volumes:
      output: /workspaces/asqi/output # Add a output volume to save the log file
    params:
      probes: ["encoding.InjectHex"]
      generations: 1
      garak_log_filename: garak_output_encoding.jsonl

  # Prompt injection attacks testing
  - id: "garak_prompt_injection"
    name: "garak_prompt_injection"
    image: "asqiengineer/test-container:garak-latest"
    systems_under_test:
      - "openai_gpt4o_mini"
    volumes:
      output: /workspaces/asqi/output
    params:
      probes: ["dan"]
      generations: 1
      garak_log_filename: garak_output_dan.jsonl
