suite_name: "Security Testing Suite with Garak"
test_suite:
  # Basic security probes using garak
  - name: "garak_encoding_probe"
    image: "my-registry/garak:latest"
    target_suts:
      - "openai_gpt4o_mini"
    params:
      probes: ["encoding.InjectHex"]
      generations: 1
    tags:
      - "security"
      - "encoding"

  # Prompt injection attacks testing
  - name: "garak_prompt_injection"
    image: "my-registry/garak:latest"
    target_suts:
      - "openai_gpt4o_mini"
    params:
      probes: ["dan"]
      generations: 1
    tags:
      - "security"
      - "injection"

  # Mock tester for baseline functionality
  - name: "mock_connectivity_test"
    image: "my-registry/mock_tester:latest"
    target_suts:
      - "openai_gpt4o_mini"
    params:
      delay_seconds: 1
    tags:
      - "connectivity"
      - "baseline"



