version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-all:
        patterns:
        - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Monitor all test_containers subdirectories with Dockerfiles
  - package-ecosystem: "docker"
    directory: "/test_containers/chatbot_simulator"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/test_containers/computer_vision"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/test_containers/cv_tester"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/test_containers/deepteam"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/test_containers/garak"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/test_containers/mock_tester"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/test_containers/trustllm"
    schedule:
      interval: "weekly"