[project]
name = "asqi"
version = "0.1.0"
description = "ASQI quality checks for AI systems"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["dbos>=1.11.0", "pydantic>=2.11.7", "pyyaml>=6.0.2"]

[dependency-groups]
dev = ["pytest>=8.4.1"]
