suite_name: "Inspect Assistants Evaluation Suite"
test_suite:

  # AssistantBench
  - name: "inspect_assistant_bench_closed_book_one_shot"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "assistant_bench_closed_book_one_shot"
      evaluation_params: {}
      limit: 2

  - name: "inspect_assistant_bench_closed_book_zero_shot"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "assistant_bench_closed_book_zero_shot"
      evaluation_params: {}
      limit: 2

  - name: "inspect_assistant_bench_web_browser"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "assistant_bench_web_browser"
      evaluation_params: {}
      limit: 2

  - name: "inspect_assistant_bench_web_search_one_shot"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "assistant_bench_web_search_one_shot"
      evaluation_params: {}
      limit: 2

  - name: "inspect_assistant_bench_web_search_zero_shot"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "assistant_bench_web_search_zero_shot"
      evaluation_params: {}
      limit: 2

  # BrowseComp
  - name: "inspect_browse_comp"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "browse_comp"
      evaluation_params: {}
      limit: 2

  # GAIA
  - name: "inspect_gaia"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "gaia"
      evaluation_params: {}
      limit: 2

  - name: "inspect_gaia_level1"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "gaia_level1"
      evaluation_params: {}
      limit: 2

  - name: "inspect_gaia_level2"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "gaia_level2"
      evaluation_params: {}
      limit: 2

  - name: "inspect_gaia_level3"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "gaia_level3"
      evaluation_params: {}
      limit: 2

  # Sycophancy
  - name: "inspect_sycophancy"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "sycophancy"
      evaluation_params: {}
      limit: 2