suite_name: "Inspect Coding Evaluation Suite"
test_suite:

  # AgentBench
  - name: "inspect_agent_bench_os"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "agent_bench_os"
      evaluation_params: {}
      limit: 2

  # ClassEval
  - name: "inspect_class_eval"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "class_eval"
      evaluation_params: {}
      limit: 2

  # DS-1000
  - name: "inspect_ds1000"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "ds1000"
      evaluation_params: {}
      limit: 2

  # HumanEval
  - name: "inspect_humaneval"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "humaneval"
      evaluation_params: {}
      limit: 2

  # MBPP
  - name: "inspect_mbpp"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "mbpp"
      evaluation_params: {}
      limit: 2

  # USACO
  - name: "inspect_usaco"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "usaco"
      evaluation_params: {}
      limit: 2