suite_name: "Inspect Cybersecurity Evaluation Suite"
test_suite:

  # CyberSecurityEval 3
  - id: "inspect_cyberseceval_3"
    name: "inspect cyberseceval 3"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "cyse3_visual_prompt_injection"
      evaluation_params: {}
      limit: 2

  # Catastrophic Cyber Capabilities Benchmark (3CB)
  - id: "inspect_threecb"
    name: "inspect threecb"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "threecb"
      evaluation_params:
        max_sample_time_mins: 1
        task_filter: python_repl_factorial10
      limit: 2

  # CyberMetric
  - id: "inspect_cybermetric_80"
    name: "inspect cybermetric 80"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "cybermetric_80"
      evaluation_params: {}
      limit: 2

  - id: "inspect_cybermetric_500"
    name: "inspect cybermetric 500"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "cybermetric_500"
      evaluation_params: {}
      limit: 2

  - id: "inspect_cybermetric_2000"
    name: "inspect cybermetric 2000"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "cybermetric_2000"
      evaluation_params: {}
      limit: 2

  - id: "inspect_cybermetric_10000"
    name: "inspect cybermetric 10000"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "cybermetric_10000"
      evaluation_params: {}
      limit: 2

  # CyberSecEval_2
  - id: "inspect_cyse2_interpreter_abuse"
    name: "inspect cyse2 interpreter abuse"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "cyse2_interpreter_abuse"
      evaluation_params: {}
      limit: 2

  - id: "inspect_cyse2_prompt_injection"
    name: "inspect cyse2 prompt injection"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "cyse2_prompt_injection"
      evaluation_params: {}
      limit: 2

  - id: "inspect_cyse2_vulnerability_exploit"
    name: "inspect cyse2 vulnerability exploit"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "cyse2_vulnerability_exploit"
      evaluation_params: {}
      limit: 2

  # GDM Dangerous Capabilities: Capture the Flag
  - id: "inspect_gdm_in_house_ctf"
    name: "inspect gdm in house ctf"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "gdm_in_house_ctf"
      evaluation_params: {}
      limit: 2

  # InterCode: Security and Coding Capture-the-Flag Challenges
  - id: "inspect_gdm_intercode_ctf"
    name: "inspect gdm intercode ctf"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "gdm_intercode_ctf"
      evaluation_params:
        max_messages: 5
        max_attempts: 3
      limit: 2

  # SEvenLLM
  - id: "inspect_sevenllm_mcq_en"
    name: "inspect sevenllm mcq en"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "sevenllm_mcq_en"
      evaluation_params: {}
      limit: 2

  - id: "inspect_sevenllm_mcq_zh"
    name: "inspect sevenllm mcq zh"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "sevenllm_mcq_zh"
      evaluation_params: {}
      limit: 2

  - id: "inspect_sevenllm_qa_en"
    name: "inspect sevenllm qa en"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "sevenllm_qa_en"
      evaluation_params: {}
      limit: 2

  - id: "inspect_sevenllm_qa_zh"
    name: "inspect sevenllm qa zh"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "sevenllm_qa_zh"
      evaluation_params: {}
      limit: 2

  # SecQA
  - id: "inspect_sec_qa_v1"
    name: "inspect sec qa v1"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "sec_qa_v1"
      evaluation_params: {}
      limit: 2

  - id: "inspect_sec_qa_v1_5_shot"
    name: "inspect sec qa v1 5 shot"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "sec_qa_v1_5_shot"
      evaluation_params: {}
      limit: 2

  - id: "inspect_sec_qa_v2"
    name: "inspect sec qa v2"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "sec_qa_v2"
      evaluation_params: {}
      limit: 2

  - id: "inspect_sec_qa_v2_5_shot"
    name: "inspect sec qa v2 5 shot"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "sec_qa_v2_5_shot"
      evaluation_params: {}
      limit: 2