suite_name: "Inspect Multimodal Evaluation Suite"
test_suite:

  # DocVQA
  - name: "inspect_docvqa"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "openai_gpt4o_mini"
    params:
      evaluation: "docvqa"
      evaluation_params: {}
      limit: 2

  # # MMIU
  # - name: "inspect_mmiu"
  #   image: "asqiengineer/test-container:inspect_evals-latest"
  #   systems_under_test:
  #     - "openai_gpt4o_mini"
  #   params:
  #     evaluation: "mmiu"
  #     evaluation_params: {}
  #     limit: 2

  # # V*Bench
  # - name: "inspect_vstar_bench_attribute_recognition"
  #   image: "asqiengineer/test-container:inspect_evals-latest"
  #   systems_under_test:
  #     - "openai_gpt4o_mini"
  #   params:
  #     evaluation: "vstar_bench_attribute_recognition"
  #     evaluation_params: {}
  #     limit: 2

  # - name: "inspect_vstar_bench_spatial_relationship_reasoning"
  #   image: "asqiengineer/test-container:inspect_evals-latest"
  #   systems_under_test:
  #     - "openai_gpt4o_mini"
  #   params:
  #     evaluation: "vstar_bench_spatial_relationship_reasoning"
  #     evaluation_params: {}
  #     limit: 2

  # # ZeroBench
  # - name: "inspect_zerobench"
  #   image: "asqiengineer/test-container:inspect_evals-latest"
  #   systems_under_test:
  #     - "openai_gpt4o_mini"
  #   params:
  #     evaluation: "zerobench"
  #     evaluation_params: {}
  #     limit: 2

  # - name: "inspect_zerobench_subquestions"
  #   image: "asqiengineer/test-container:inspect_evals-latest"
  #   systems_under_test:
  #     - "openai_gpt4o_mini"
  #   params:
  #     evaluation: "zerobench_subquestions"
  #     evaluation_params: {}
  #     limit: 2