suite_name: "Inspect Safeguards Evaluation Suite"
test_suite:

  # AbstentionBench
  - id: "inspect_abstention_bench"
    name: "inspect abstention bench"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "abstention_bench"
      evaluation_params: {
        "dataset_name": "alcuna",
        "grader_model": "openai/gpt-4o",
        "use_fast_sampling": true
      }
      limit: 2

  # AgentDojo
  - id: "inspect_agentdojo"
    name: "inspect agentdojo"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "agentdojo"
      evaluation_params: {}
      limit: 2

  # AgentHarm
  - id: "inspect_agentharm"
    name: "inspect agentharm"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "agentharm"
      evaluation_params: {}
      limit: 2

  - id: "inspect_agentharm_benign"
    name: "inspect agentharm benign"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "agentharm_benign"
      evaluation_params: {}
      limit: 2

  # LAB-Bench
  - id: "inspect_lab_bench_cloning_scenarios"
    name: "inspect lab bench cloning scenarios"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "lab_bench_cloning_scenarios"
      evaluation_params: {}
      limit: 2

  - id: "inspect_lab_bench_dbqa"
    name: "inspect lab bench dbqa"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "lab_bench_dbqa"
      evaluation_params: {}
      limit: 2

  - id: "inspect_lab_bench_figqa"
    name: "inspect lab bench figqa"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "lab_bench_figqa"
      evaluation_params: {}
      limit: 2

  - id: "inspect_lab_bench_litqa"
    name: "inspect lab bench litqa"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "lab_bench_litqa"
      evaluation_params: {}
      limit: 2

  - id: "inspect_lab_bench_protocolqa"
    name: "inspect lab bench protocolqa"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "lab_bench_protocolqa"
      evaluation_params: {}
      limit: 2

  - id: "inspect_lab_bench_seqqa"
    name: "inspect lab bench seqqa"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "lab_bench_seqqa"
      evaluation_params: {}
      limit: 2

  # MASK
  - id: "inspect_mask"
    name: "inspect mask"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "mask"
      evaluation_params: {}
      limit: 2

  # Make Me Pay
  - id: "inspect_make_me_pay"
    name: "inspect make me pay"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "make_me_pay"
      evaluation_params: {}
      limit: 2

  # StereoSet
  - id: "inspect_stereoset"
    name: "inspect stereoset"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "stereoset"
      evaluation_params: {}
      limit: 2

  # StrongREJECT
  - id: "inspect_strong_reject"
    name: "inspect strong reject"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "strong_reject"
      evaluation_params: {}
      limit: 2

  # WMDP
  - id: "inspect_wmdp_bio"
    name: "inspect wmdp bio"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "wmdp_bio"
      evaluation_params: {}
      limit: 2

  - id: "inspect_wmdp_chem"
    name: "inspect wmdp chem"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "wmdp_chem"
      evaluation_params: {}
      limit: 2

  - id: "inspect_wmdp_cyber"
    name: "inspect wmdp cyber"
    image: "asqiengineer/test-container:inspect_evals-latest"
    systems_under_test:
      - "nova_lite"
    params:
      evaluation: "wmdp_cyber"
      evaluation_params: {}
      limit: 2