# yaml-language-server: $schema=../../src/asqi/schemas/asqi_score_card.schema.json
score_card_name: "Approved ASQI"
indicators:
  - name: "Mock test success requirement"
    apply_to:
      test_name: "run_mock_on_compatible_sut"
    metric: "success"
    assessment:
      - {
          outcome: "PASS",
          condition: "equal_to",
          threshold: true,
          description: "You can associate an outcome with a more business friendly description",
        }
      - {
          outcome: "FAIL",
          condition: "equal_to",
          threshold: false,
          description: "It seems that the mock test might have failed",
        }

  - name: "Example of 2nd indicator"
    apply_to:
      test_name: "run_mock_on_compatible_sut"
    metric: "score"
    assessment:
      - { outcome: "A", condition: "greater_equal", threshold: 0.9 }
      - { outcome: "B", condition: "greater_equal", threshold: 0.8 }
      - { outcome: "C", condition: "less_than", threshold: 0.8 }
