systems_under_test:
  object_detection:
    type: "object_detection_api"
    params:
      endpoint: "${LOCAL_ENDPOINT}"  # FULL URL to POST the image
      iou_thr: 0.5                         # Eval-time IoU threshold for GT ↔ pred matching
      mode : "local"
      api_params:                          # Request details forwarded to requests.post(**kwargs) to communicate with the API
        input_field: "image"               # query key for URL OR JSON key for base64
        params:                            # Query-string args appended to the URL:
          conf: 0.3                        #  -> model confidence threshold (API-side)
          iou: 0.5                         #  -> NMS IoU threshold (API-side)
          timeout : 30.0                   #  -> Request timeout in seconds
  roboflow_object_detection:
    type: "object_detection_api"
    params:
      endpoint: "${ROBOFLOW_ENDPOINT}"  # FULL URL to POST the image from .env
      iou_thr: 0.5
      mode : "roboflow"                         
      api_params:                        
        input_field: "data"               
        params:                      
          api_key: "${ROBOFLOW_API_KEY}" # Injected from .env at runtime          
        headers:
          Content-Type : "application/x-www-form-urlencoded"
