systems_under_test:
  object_detection:
    type: "object_detection_api"
    params:
      endpoint: "${LOCAL_ENDPOINT}"  # FULL URL to POST the image from .env
      iou_thr: 0.5                         # Eval-time IoU threshold for GT ↔ pred matching
      mode : "local"
      api_params:                          # Request details forwarded to requests.post(**kwargs) to communicate with the API
        input_field: "image"               # query key for URL OR JSON key for base64
        params:                           
          conf: 0.3                        
          iou: 0.5                         
          timeout : 30.0                   
        headers:                          
          Content-Type : "application/json" #  -> API expects base64-encoded image in JSON payload
  roboflow_object_detection: # reference for Roboflow API usage : https://docs.roboflow.com/deploy/serverless/object-detection
    type: "object_detection_api"
    params:
      endpoint: "${ROBOFLOW_ENDPOINT}"  # FULL URL to POST the image from .env
      iou_thr: 0.5
      mode : "roboflow"                         
      api_params:                        
        input_field: "data"               
        params:                      
          api_key: "${ROBOFLOW_API_KEY}" # Injected from .env at runtime          
        headers:
          Content-Type : "application/x-www-form-urlencoded"
  huggingface_object_detection: # reference for Huggingface API usage : https://huggingface.co/docs/inference-providers/en/tasks/object-detection
    type: "object_detection_api"
    params:
      endpoint: "${HUGGINGFACE_ENDPOINT}"  # FULL URL to POST the image from .env
      iou_thr: 0.5
      mode : "huggingface"                         
      api_params:                        
        input_field: "data"               
        params:                      
          api_key: "${HUGGINGFACE_API_KEY}" # Injected from .env at runtime          
        headers:
          Authorization : "Bearer ${HUGGINGFACE_API_KEY}"
          Content-Type: "image/jpeg"
  ultralytics_object_detection: #reference for Ultralytics API usage : https://docs.ultralytics.com/hub/inference-api/#python
    type: "object_detection_api"
    params:
      endpoint: "${ULTRALYTICS_ENDPOINT}"  # FULL URL to POST the image from .env
      iou_thr: 0.5
      mode : "ultralytics"                         
      api_params:                        
        input_field: "file"               
        params:                          
          model : "https://hub.ultralytics.com/models/7wzkDSKNMcwkPTs8ZVJC" #YOLO11n
        headers:
          x-api-key : "${ULTRALYTICS_API_KEY}"
          Content-Type: "multipart/form-data"