name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  test:
    uses: ./.github/workflows/test.yaml

  security:
    uses: ./.github/workflows/security.yaml
  
  build-publish:
    needs: [ lint, test,  security ]
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit