name: Publish test containers

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false

env:
  REGISTRY: docker.io
  IMAGE_NAME: asqiengineer/test-container

jobs:
  determine-changed:
    name: Determine changed containers
    if: startsWith(github.ref, 'refs/heads/') || github.event_name == 'pull_request'
    runs-on: self-hosted
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      unique_matrix: ${{ steps.set-matrix.outputs.unique_matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62
        with:
          files: |
            test_containers/**

      - name: Build matrix from changed test container folders
        id: set-matrix
        run: |
          set -euo pipefail
          # Split the changed files string into array
          IFS=' ' read -ra files <<< "${{ steps.changed-files.outputs.all_changed_files }}"
          declare -A dirs=()
          for file in "${files[@]}"; do
            # Expect paths like test_containers/<name>/...
            if [[ "$file" == test_containers/*/* ]]; then
              name=$(echo "$file" | awk -F/ '{print $2}')
              dirs["$name"]=1
            fi
          done

          if [ ${#dirs[@]} -eq 0 ]; then
            echo "No test container directories changed."
            echo 'matrix={"include":[{"name":"noop","skip":true}]}' >> "$GITHUB_OUTPUT"
            exit 0
          fi

          json='{"include":['
          first=1
          for d in "${!dirs[@]}"; do
            for platform in "linux/amd64" "linux/arm64"; do
              platform_pair="${platform//\//-}"
              entry='{"name":"'"$d"'","platform":"'"$platform"'","platform_pair":"'"$platform_pair"'"}'
              if [ $first -eq 1 ]; then
                json+="$entry"
                first=0
              else
                json+=",$entry"
              fi
            done
          done
          json+=']}'

          echo "Detected changed containers matrix: $json"
          echo "matrix=$json" >> "$GITHUB_OUTPUT"
          
          # Create unique names matrix for publishing
          unique_json='{"include":['
          first=1
          for d in "${!dirs[@]}"; do
            entry='{"name":"'"$d"'"}'
            if [ $first -eq 1 ]; then
              unique_json+="$entry"
              first=0
            else
              unique_json+=",$entry"
            fi
          done
          unique_json+=']}'
          echo "unique_matrix=$unique_json" >> "$GITHUB_OUTPUT"

  build-and-test-changed:
    name: Build and test changed containers
    needs: determine-changed
    if: startsWith(github.ref, 'refs/heads/') || github.event_name == 'pull_request'
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.determine-changed.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: No changes to test containers (noop)
        if: ${{ matrix.skip == true }}
        run: echo "No changed test containers detected; skipping build/test/publish."

      - name: Set up QEMU
        if: ${{ matrix.skip != true }}
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: ${{ matrix.skip != true }}
        uses: docker/setup-buildx-action@v3

      - name: Build image for ${{ matrix.name }} (${{ matrix.platform }})
        if: ${{ matrix.skip != true }}
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ./test_containers/${{ matrix.name }}
          platforms: ${{ matrix.platform }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.name }}-sha-${{ github.sha }}-${{ matrix.platform_pair }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache-${{ matrix.name }}-${{ matrix.platform_pair }}
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache-${{ matrix.name }}-${{ matrix.platform_pair }},mode=max
          outputs: type=docker,dest=/tmp/image-${{ matrix.name }}-${{ matrix.platform_pair }}.tar

      - name: Smoke test ${{ matrix.name }} (${{ matrix.platform }})
        if: ${{ matrix.skip != true }}
        run: |
          docker load -i /tmp/image-${{ matrix.name }}-${{ matrix.platform_pair }}.tar
          echo "Running smoke test for ${{ matrix.name }} (${{ matrix.platform }}) with --help command..."
          docker run --rm --platform ${{ matrix.platform }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.name }}-sha-${GITHUB_SHA}-${{ matrix.platform_pair }} --help

      - name: Upload Docker image as artifact (${{ matrix.name }}-${{ matrix.platform_pair }})
        if: ${{ matrix.skip != true && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository) }}
        uses: actions/upload-artifact@v5
        with:
          name: docker-image-${{ matrix.name }}-${{ matrix.platform_pair }}
          path: /tmp/image-${{ matrix.name }}-${{ matrix.platform_pair }}.tar
          retention-days: 1

  publish-changed:
    name: Publish changed containers
    needs: [determine-changed, build-and-test-changed]
    if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/heads/')
    runs-on: self-hosted
    environment:
      name: publish-docker-registry
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.determine-changed.outputs.unique_matrix) }}
    steps:
      - name: No changes to publish (noop)
        if: ${{ matrix.skip == true }}
        run: echo "No changed test containers to publish."

      - name: Download Docker image artifacts (${{ matrix.name }})
        if: ${{ matrix.skip != true }}
        uses: actions/download-artifact@v6
        with:
          path: /tmp
          pattern: docker-image-${{ matrix.name }}-*
          merge-multiple: true

      - name: Set up Docker Buildx
        if: ${{ matrix.skip != true }}
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: ${{ matrix.skip != true }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push multi-platform image for ${{ matrix.name }}
        if: ${{ matrix.skip != true }}
        run: |
          set -euo pipefail
          
          # Load both platform images and push them
          docker load -i /tmp/image-${{ matrix.name }}-linux-amd64.tar
          docker load -i /tmp/image-${{ matrix.name }}-linux-arm64.tar
          
          AMD64_SRC=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.name }}-sha-${GITHUB_SHA}-linux-amd64
          ARM64_SRC=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.name }}-sha-${GITHUB_SHA}-linux-arm64
          
          # Push individual platform images
          docker push --quiet "${AMD64_SRC}"
          docker push --quiet "${ARM64_SRC}"
          
          # Get digests for manifest creation
          AMD64_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' "${AMD64_SRC}" | cut -d'@' -f2)
          ARM64_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' "${ARM64_SRC}" | cut -d'@' -f2)
          
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            LATEST=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.name }}-latest
            
            # Create manifest list for latest tag
            docker buildx imagetools create \
              -t "${LATEST}" \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${AMD64_DIGEST} \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${ARM64_DIGEST}
          fi

  build-and-test-tag:
    name: Build and test tagged container
    if: startsWith(github.ref, 'refs/tags/test_containers/')
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      FULL_REF: ${{ github.ref_name }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    outputs:
      name: ${{ steps.parse.outputs.name }}
      version: ${{ steps.parse.outputs.version }}
    steps:
      - name: Prepare platform variables
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Parse tag
        id: parse
        run: |
          set -euo pipefail
          # Tag format expected: test_containers/<name>/<version>
          IFS='/' read -r root name version <<< "${FULL_REF}"
          if [ "${root}" != "test_containers" ] || [ -z "${name}" ] || [ -z "${version}" ]; then
            echo "Tag '${FULL_REF}' does not match required format: test_containers/<name>/<version>" >&2
            exit 1
          fi
          echo "name=${name}" >> "$GITHUB_OUTPUT"
          echo "version=${version}" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v5

      - name: Verify Dockerfile exists
        run: |
          if [ ! -f "test_containers/${{ steps.parse.outputs.name }}/Dockerfile" ]; then
            echo "Dockerfile not found for container '${{ steps.parse.outputs.name }}'" >&2
            exit 1
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image for ${{ steps.parse.outputs.name }} (${{ matrix.platform }})
        id: build_tag
        uses: docker/build-push-action@v6
        with:
          context: ./test_containers/${{ steps.parse.outputs.name }}
          platforms: ${{ matrix.platform }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.parse.outputs.name }}-sha-${{ github.sha }}-${{ env.PLATFORM_PAIR }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache-${{ steps.parse.outputs.name }}-${{ env.PLATFORM_PAIR }}
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache-${{ steps.parse.outputs.name }}-${{ env.PLATFORM_PAIR }},mode=max
          outputs: type=docker,dest=/tmp/image-${{ steps.parse.outputs.name }}-${{ env.PLATFORM_PAIR }}.tar

      - name: Smoke test ${{ steps.parse.outputs.name }} (${{ matrix.platform }})
        run: |
          docker load -i /tmp/image-${{ steps.parse.outputs.name }}-${{ env.PLATFORM_PAIR }}.tar
          echo "Running smoke test for ${{ steps.parse.outputs.name }} (${{ matrix.platform }}) with --help command..."
          docker run --rm --platform ${{ matrix.platform }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.parse.outputs.name }}-sha-${GITHUB_SHA}-${{ env.PLATFORM_PAIR }} --help

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v5
        with:
          name: docker-image-${{ steps.parse.outputs.name }}-${{ env.PLATFORM_PAIR }}
          path: /tmp/image-${{ steps.parse.outputs.name }}-${{ env.PLATFORM_PAIR }}.tar
          retention-days: 1

  publish-tag:
    name: Publish tagged container
    needs: build-and-test-tag
    if: startsWith(github.ref, 'refs/tags/test_containers/')
    runs-on: self-hosted
    environment:
      name: publish-docker-registry
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      - name: Download Docker image artifacts
        uses: actions/download-artifact@v6
        with:
          path: /tmp
          pattern: docker-image-${{ needs.build-and-test-tag.outputs.name }}-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push multi-platform image ${{ needs.build-and-test-tag.outputs.name }}:${{ needs.build-and-test-tag.outputs.version }}
        id: push
        run: |
          set -euo pipefail
          NAME='${{ needs.build-and-test-tag.outputs.name }}'
          VERSION='${{ needs.build-and-test-tag.outputs.version }}'
          
          # Load both platform images and push them
          docker load -i "/tmp/image-${NAME}-linux-amd64.tar"
          docker load -i "/tmp/image-${NAME}-linux-arm64.tar"
          
          AMD64_SRC=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${NAME}-sha-${GITHUB_SHA}-linux-amd64
          ARM64_SRC=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${NAME}-sha-${GITHUB_SHA}-linux-arm64
          
          # Push individual platform images
          docker push --quiet "${AMD64_SRC}"
          docker push --quiet "${ARM64_SRC}"
          
          # Get digests for manifest creation
          AMD64_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' "${AMD64_SRC}" | cut -d'@' -f2)
          ARM64_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' "${ARM64_SRC}" | cut -d'@' -f2)
          
          DEST=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${NAME}-${VERSION}
          
          # Create manifest list for versioned tag
          docker buildx imagetools create \
            -t "${DEST}" \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${AMD64_DIGEST} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${ARM64_DIGEST}
          
          # Get final manifest digest for attestation
          DIGEST=$(docker buildx imagetools inspect "${DEST}" --format '{{.Manifest.Digest}}')
          echo "digest=${DIGEST}" >> "$GITHUB_OUTPUT"

# activate when public GH repo
#      - name: Attest
#        uses: actions/attest-build-provenance@v3
#        id: attest
#        with:
#          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#          subject-digest: ${{ steps.push.outputs.digest }}
#          push-to-registry: true
